---
- hosts: kibana
  become: yes
  tasks:

  - name: Update Apt and Upgrade Apt
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install Java jdk
    apt:
      name: openjdk-8-jdk

  - name: Install the gpg key for metic
    apt_key:
      url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

  - name: download apt transport
    apt:
      name: apt-transport-https

  - name: Install the kibana repository
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"

  - name: Update Apt
    apt:
      update_cache: yes

  - name: download kibana
    apt:
      name: kibana

  - name: copy kibana file
    copy:
      src: /home/vagrant/ansibles/kibana.yml
      dest: /etc/kibana/kibana.yml
      mode: 0777

  - name: start kibana
    systemd:
      name: kibana
      state: reloaded
      enabled: yes
