version: "3.7"
services:

  lb:
    build:
      context: ./
      dockerfile: lbdockerfile
    container_name: lb
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
      - db1
      - db2
      - app
      - app1
      - app2

  app:
    image: dockernotes_app
    container_name: app
    restart: always
    environment:
      DB_HOST: mongodb://db:27017,db1:27017,db2:27017/posts?replicaSet=rs0
    depends_on:
      - db
      - db1
      - db2

  app1:
    image: dockernotes_app
    container_name: app1
    restart: always
    environment:
      DB_HOST: mongodb://db:27017,db1:27017,db2:27017/posts?replicaSet=rs0
    depends_on:
      - db
      - db1
      - db2

  app2:
    image: dockernotes_app
    container_name: app2
    restart: always
    environment:
      DB_HOST: mongodb://db:27017,db1:27017,db2:27017/posts?replicaSet=rs0
    depends_on:
      - db
      - db1
      - db2

  db_init:
    image: dockernotes_db
    container_name: db_init
    command: ./setup.sh
    depends_on:
      - db
      - db1
      - db2

  db:
    image: mongo
    container_name: db
    restart: always
    command: mongod --bind_ip_all --replSet rs0

  db1:
    image: mongo
    container_name: db1
    restart: always
    command: mongod --bind_ip_all --replSet rs0

  db2:
    image: mongo
    container_name: db2
    restart: always
    command: mongod --bind_ip_all --replSet rs0
