version: "3.7"
services:
  app:
    image: dockernotes_app
    container_name: app
    restart: always
    environment:
      DB_HOST: mongodb://db:27017,db1:27017,db2:27017/posts?replicaSet=rs0
    ports:
      - "80:3000"
    depends_on:
      - db
      - db1
      - db2
  initcontainer:
    image: dockernotes_db
    container_name: initcontainer
    command: ./setup.sh
    depends_on:
      - db
      - db1
      - db2
  db:
    image: dockernotes_db
    container_name: db
    restart: always
    command: mongod --bind_ip_all --replSet rs0
  db1:
    image: mongo
    container_name: db1
    restart: always
    command: mongod --bind_ip_all --replSet rs0

  db2:
    image: mongo
    container_name: db2
    restart: always
    command: mongod --bind_ip_all --replSet rs0
